export class EnvConstants {
  static readonly API_VERSION: string = 'API_VERSION';
  static readonly PORT: string = 'PORT';
  static readonly LOG_LEVELS: string = 'LOG_LEVELS';
  static readonly WEBHOOK_NOTIFICATION_URL: string = 'WEBHOOK_NOTIFICATION_URL';
  static readonly NOTIFICATION_SIGNATURE: string = 'NOTIFICATION_SIGNATURE';
  static readonly NOTIFICATION_BASIC_AUTH: string = 'NOTIFICATION_BASIC_AUTH';
  static readonly NOTIFICATION_TO_EMAIL_TEST: string =
    'NOTIFICATION_TO_EMAIL_TEST';
  static readonly NOTIFICATION_FROM_EMAIL: string = 'NOTIFICATION_FROM_EMAIL';
  static readonly AUTH_BEARER_SECRET: string = 'AUTH_BEARER_SECRET';
  static readonly AUTH_BEARER_EXPIRES_IN_TIME_TOKEN_BEARER: string =
    'AUTH_BEARER_EXPIRES_IN_TIME_TOKEN_BEARER';
  static readonly SF_DEFAULT_WEBHOOK_USERNAME = 'SF_DEFAULT_WEBHOOK_USERNAME';
  static readonly SF_DEFAULT_WEBHOOK_PASSWORD = 'SF_DEFAULT_WEBHOOK_PASSWORD';
  static readonly PARTICIPANTS_SYNC_BATCH_INTERVAL = 'PARTICIPANTS_SYNC_BATCH_INTERVAL';
  static readonly PARTICIPANTS_SYNC_BATCH_FINAL_PAUSE = 'PARTICIPANTS_SYNC_BATCH_FINAL_PAUSE';
  static readonly PARTICIPANTS_SYNC_BATCH_SIZE = 'PARTICIPANTS_SYNC_BATCH_SIZE';
  static readonly SAVE_PARTICIPANT_SYNC_BATCH_TRANSACTIONS = 'SAVE_PARTICIPANT_SYNC_BATCH_TRANSACTIONS';
  static readonly REDIRECT_NOTIFICATIONS_DEVICES = 'REDIRECT_NOTIFICATIONS_DEVICES';
  static readonly ALLOW_SUBSCRIBE_TO_NOTIFICATIONS_WITHOUT_CLIENT_WEBHOOK = 'ALLOW_SUBSCRIBE_TO_NOTIFICATIONS_WITHOUT_CLIENT_WEBHOOK';
  static readonly ALL_NOTIFICATIONS = 'ALL_NOTIFICATIONS';
}
